/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AddressV1DomainAddress
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class AddressV1DomainAddress {
  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("flatUnitNr")
  private String flatUnitNr = null;

  @JsonProperty("flatUnitNrSuffix")
  private String flatUnitNrSuffix = null;

  @JsonProperty("floorLevelNr")
  private String floorLevelNr = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("parameters")
  private Map<String, String> parameters = null;

  @JsonProperty("postcode")
  private String postcode = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("referenceId")
  private String referenceId = null;

  @JsonProperty("referenceSystem")
  private String referenceSystem = null;

  @JsonProperty("streetName")
  private String streetName = null;

  @JsonProperty("streetNr")
  private String streetNr = null;

  @JsonProperty("streetNrLast")
  private String streetNrLast = null;

  @JsonProperty("streetNrLastSuffix")
  private String streetNrLastSuffix = null;

  @JsonProperty("streetNrSuffix")
  private String streetNrSuffix = null;

  @JsonProperty("streetType")
  private String streetType = null;

  @JsonProperty("validated")
  private Boolean validated = null;

  public AddressV1DomainAddress city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressV1DomainAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public AddressV1DomainAddress flatUnitNr(String flatUnitNr) {
    this.flatUnitNr = flatUnitNr;
    return this;
  }

   /**
   * Get flatUnitNr
   * @return flatUnitNr
  **/
  @ApiModelProperty(value = "")
  public String getFlatUnitNr() {
    return flatUnitNr;
  }

  public void setFlatUnitNr(String flatUnitNr) {
    this.flatUnitNr = flatUnitNr;
  }

  public AddressV1DomainAddress flatUnitNrSuffix(String flatUnitNrSuffix) {
    this.flatUnitNrSuffix = flatUnitNrSuffix;
    return this;
  }

   /**
   * Get flatUnitNrSuffix
   * @return flatUnitNrSuffix
  **/
  @ApiModelProperty(value = "")
  public String getFlatUnitNrSuffix() {
    return flatUnitNrSuffix;
  }

  public void setFlatUnitNrSuffix(String flatUnitNrSuffix) {
    this.flatUnitNrSuffix = flatUnitNrSuffix;
  }

  public AddressV1DomainAddress floorLevelNr(String floorLevelNr) {
    this.floorLevelNr = floorLevelNr;
    return this;
  }

   /**
   * Get floorLevelNr
   * @return floorLevelNr
  **/
  @ApiModelProperty(value = "")
  public String getFloorLevelNr() {
    return floorLevelNr;
  }

  public void setFloorLevelNr(String floorLevelNr) {
    this.floorLevelNr = floorLevelNr;
  }

  public AddressV1DomainAddress id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AddressV1DomainAddress parameters(Map<String, String> parameters) {
    this.parameters = parameters;
    return this;
  }

  public AddressV1DomainAddress putParametersItem(String key, String parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<String, String>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getParameters() {
    return parameters;
  }

  public void setParameters(Map<String, String> parameters) {
    this.parameters = parameters;
  }

  public AddressV1DomainAddress postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @ApiModelProperty(value = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public AddressV1DomainAddress province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  @ApiModelProperty(value = "")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public AddressV1DomainAddress referenceId(String referenceId) {
    this.referenceId = referenceId;
    return this;
  }

   /**
   * Get referenceId
   * @return referenceId
  **/
  @ApiModelProperty(value = "")
  public String getReferenceId() {
    return referenceId;
  }

  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }

  public AddressV1DomainAddress referenceSystem(String referenceSystem) {
    this.referenceSystem = referenceSystem;
    return this;
  }

   /**
   * Get referenceSystem
   * @return referenceSystem
  **/
  @ApiModelProperty(value = "")
  public String getReferenceSystem() {
    return referenceSystem;
  }

  public void setReferenceSystem(String referenceSystem) {
    this.referenceSystem = referenceSystem;
  }

  public AddressV1DomainAddress streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

   /**
   * Get streetName
   * @return streetName
  **/
  @ApiModelProperty(value = "")
  public String getStreetName() {
    return streetName;
  }

  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public AddressV1DomainAddress streetNr(String streetNr) {
    this.streetNr = streetNr;
    return this;
  }

   /**
   * Get streetNr
   * @return streetNr
  **/
  @ApiModelProperty(value = "")
  public String getStreetNr() {
    return streetNr;
  }

  public void setStreetNr(String streetNr) {
    this.streetNr = streetNr;
  }

  public AddressV1DomainAddress streetNrLast(String streetNrLast) {
    this.streetNrLast = streetNrLast;
    return this;
  }

   /**
   * Get streetNrLast
   * @return streetNrLast
  **/
  @ApiModelProperty(value = "")
  public String getStreetNrLast() {
    return streetNrLast;
  }

  public void setStreetNrLast(String streetNrLast) {
    this.streetNrLast = streetNrLast;
  }

  public AddressV1DomainAddress streetNrLastSuffix(String streetNrLastSuffix) {
    this.streetNrLastSuffix = streetNrLastSuffix;
    return this;
  }

   /**
   * Get streetNrLastSuffix
   * @return streetNrLastSuffix
  **/
  @ApiModelProperty(value = "")
  public String getStreetNrLastSuffix() {
    return streetNrLastSuffix;
  }

  public void setStreetNrLastSuffix(String streetNrLastSuffix) {
    this.streetNrLastSuffix = streetNrLastSuffix;
  }

  public AddressV1DomainAddress streetNrSuffix(String streetNrSuffix) {
    this.streetNrSuffix = streetNrSuffix;
    return this;
  }

   /**
   * Get streetNrSuffix
   * @return streetNrSuffix
  **/
  @ApiModelProperty(value = "")
  public String getStreetNrSuffix() {
    return streetNrSuffix;
  }

  public void setStreetNrSuffix(String streetNrSuffix) {
    this.streetNrSuffix = streetNrSuffix;
  }

  public AddressV1DomainAddress streetType(String streetType) {
    this.streetType = streetType;
    return this;
  }

   /**
   * Get streetType
   * @return streetType
  **/
  @ApiModelProperty(value = "")
  public String getStreetType() {
    return streetType;
  }

  public void setStreetType(String streetType) {
    this.streetType = streetType;
  }

  public AddressV1DomainAddress validated(Boolean validated) {
    this.validated = validated;
    return this;
  }

   /**
   * Get validated
   * @return validated
  **/
  @ApiModelProperty(value = "")
  public Boolean isValidated() {
    return validated;
  }

  public void setValidated(Boolean validated) {
    this.validated = validated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressV1DomainAddress addressV1DomainAddress = (AddressV1DomainAddress) o;
    return Objects.equals(this.city, addressV1DomainAddress.city) &&
        Objects.equals(this.country, addressV1DomainAddress.country) &&
        Objects.equals(this.flatUnitNr, addressV1DomainAddress.flatUnitNr) &&
        Objects.equals(this.flatUnitNrSuffix, addressV1DomainAddress.flatUnitNrSuffix) &&
        Objects.equals(this.floorLevelNr, addressV1DomainAddress.floorLevelNr) &&
        Objects.equals(this.id, addressV1DomainAddress.id) &&
        Objects.equals(this.parameters, addressV1DomainAddress.parameters) &&
        Objects.equals(this.postcode, addressV1DomainAddress.postcode) &&
        Objects.equals(this.province, addressV1DomainAddress.province) &&
        Objects.equals(this.referenceId, addressV1DomainAddress.referenceId) &&
        Objects.equals(this.referenceSystem, addressV1DomainAddress.referenceSystem) &&
        Objects.equals(this.streetName, addressV1DomainAddress.streetName) &&
        Objects.equals(this.streetNr, addressV1DomainAddress.streetNr) &&
        Objects.equals(this.streetNrLast, addressV1DomainAddress.streetNrLast) &&
        Objects.equals(this.streetNrLastSuffix, addressV1DomainAddress.streetNrLastSuffix) &&
        Objects.equals(this.streetNrSuffix, addressV1DomainAddress.streetNrSuffix) &&
        Objects.equals(this.streetType, addressV1DomainAddress.streetType) &&
        Objects.equals(this.validated, addressV1DomainAddress.validated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, country, flatUnitNr, flatUnitNrSuffix, floorLevelNr, id, parameters, postcode, province, referenceId, referenceSystem, streetName, streetNr, streetNrLast, streetNrLastSuffix, streetNrSuffix, streetType, validated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressV1DomainAddress {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    flatUnitNr: ").append(toIndentedString(flatUnitNr)).append("\n");
    sb.append("    flatUnitNrSuffix: ").append(toIndentedString(flatUnitNrSuffix)).append("\n");
    sb.append("    floorLevelNr: ").append(toIndentedString(floorLevelNr)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("    referenceSystem: ").append(toIndentedString(referenceSystem)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    streetNr: ").append(toIndentedString(streetNr)).append("\n");
    sb.append("    streetNrLast: ").append(toIndentedString(streetNrLast)).append("\n");
    sb.append("    streetNrLastSuffix: ").append(toIndentedString(streetNrLastSuffix)).append("\n");
    sb.append("    streetNrSuffix: ").append(toIndentedString(streetNrSuffix)).append("\n");
    sb.append("    streetType: ").append(toIndentedString(streetType)).append("\n");
    sb.append("    validated: ").append(toIndentedString(validated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

