/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import se.telia.infonova.model.ApiModelV1CommonsDomainOverrider;
import se.telia.infonova.model.ApiModelV1CommonsDomainPriceAdjustment;

/**
 * ApiModelV1CommonsDomainPrice
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ApiModelV1CommonsDomainPrice {
  @JsonProperty("adHocPaymentRequired")
  private Boolean adHocPaymentRequired = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("overrider")
  private ApiModelV1CommonsDomainOverrider overrider = null;

  @JsonProperty("priceAdjustment")
  private ApiModelV1CommonsDomainPriceAdjustment priceAdjustment = null;

  public ApiModelV1CommonsDomainPrice adHocPaymentRequired(Boolean adHocPaymentRequired) {
    this.adHocPaymentRequired = adHocPaymentRequired;
    return this;
  }

   /**
   * Get adHocPaymentRequired
   * @return adHocPaymentRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isAdHocPaymentRequired() {
    return adHocPaymentRequired;
  }

  public void setAdHocPaymentRequired(Boolean adHocPaymentRequired) {
    this.adHocPaymentRequired = adHocPaymentRequired;
  }

  public ApiModelV1CommonsDomainPrice id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiModelV1CommonsDomainPrice name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApiModelV1CommonsDomainPrice overrider(ApiModelV1CommonsDomainOverrider overrider) {
    this.overrider = overrider;
    return this;
  }

   /**
   * Get overrider
   * @return overrider
  **/
  @ApiModelProperty(value = "")
  public ApiModelV1CommonsDomainOverrider getOverrider() {
    return overrider;
  }

  public void setOverrider(ApiModelV1CommonsDomainOverrider overrider) {
    this.overrider = overrider;
  }

  public ApiModelV1CommonsDomainPrice priceAdjustment(ApiModelV1CommonsDomainPriceAdjustment priceAdjustment) {
    this.priceAdjustment = priceAdjustment;
    return this;
  }

   /**
   * Get priceAdjustment
   * @return priceAdjustment
  **/
  @ApiModelProperty(value = "")
  public ApiModelV1CommonsDomainPriceAdjustment getPriceAdjustment() {
    return priceAdjustment;
  }

  public void setPriceAdjustment(ApiModelV1CommonsDomainPriceAdjustment priceAdjustment) {
    this.priceAdjustment = priceAdjustment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiModelV1CommonsDomainPrice apiModelV1CommonsDomainPrice = (ApiModelV1CommonsDomainPrice) o;
    return Objects.equals(this.adHocPaymentRequired, apiModelV1CommonsDomainPrice.adHocPaymentRequired) &&
        Objects.equals(this.id, apiModelV1CommonsDomainPrice.id) &&
        Objects.equals(this.name, apiModelV1CommonsDomainPrice.name) &&
        Objects.equals(this.overrider, apiModelV1CommonsDomainPrice.overrider) &&
        Objects.equals(this.priceAdjustment, apiModelV1CommonsDomainPrice.priceAdjustment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adHocPaymentRequired, id, name, overrider, priceAdjustment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiModelV1CommonsDomainPrice {\n");
    
    sb.append("    adHocPaymentRequired: ").append(toIndentedString(adHocPaymentRequired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    overrider: ").append(toIndentedString(overrider)).append("\n");
    sb.append("    priceAdjustment: ").append(toIndentedString(priceAdjustment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

