/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import se.telia.infonova.model.ApiModelV1CommonsDomainDiscountTieringLevel;
import se.telia.infonova.model.ApiModelV1CommonsDomainFundReference;

/**
 * ApiModelV1CommonsDomainPriceAdjustment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ApiModelV1CommonsDomainPriceAdjustment {
  @JsonProperty("allowanceAmount")
  private java.math.BigDecimal allowanceAmount = null;

  @JsonProperty("billText")
  private String billText = null;

  @JsonProperty("contractEndDate")
  private Date contractEndDate = null;

  @JsonProperty("discountTieringLevels")
  private List<ApiModelV1CommonsDomainDiscountTieringLevel> discountTieringLevels = null;

  @JsonProperty("flagFallAmount")
  private java.math.BigDecimal flagFallAmount = null;

  @JsonProperty("fund")
  private ApiModelV1CommonsDomainFundReference fund = null;

  @JsonProperty("fundAmount")
  private java.math.BigDecimal fundAmount = null;

  @JsonProperty("invoiceText")
  private String invoiceText = null;

  @JsonProperty("loyaltyPoints")
  private Integer loyaltyPoints = null;

  @JsonProperty("netCharge")
  private java.math.BigDecimal netCharge = null;

  @JsonProperty("numberOfPayments")
  private Integer numberOfPayments = null;

  @JsonProperty("previousNetCharge")
  private java.math.BigDecimal previousNetCharge = null;

  @JsonProperty("terminationCharge")
  private java.math.BigDecimal terminationCharge = null;

  public ApiModelV1CommonsDomainPriceAdjustment allowanceAmount(java.math.BigDecimal allowanceAmount) {
    this.allowanceAmount = allowanceAmount;
    return this;
  }

   /**
   * Get allowanceAmount
   * @return allowanceAmount
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getAllowanceAmount() {
    return allowanceAmount;
  }

  public void setAllowanceAmount(java.math.BigDecimal allowanceAmount) {
    this.allowanceAmount = allowanceAmount;
  }

  public ApiModelV1CommonsDomainPriceAdjustment billText(String billText) {
    this.billText = billText;
    return this;
  }

   /**
   * Get billText
   * @return billText
  **/
  @ApiModelProperty(value = "")
  public String getBillText() {
    return billText;
  }

  public void setBillText(String billText) {
    this.billText = billText;
  }

  public ApiModelV1CommonsDomainPriceAdjustment contractEndDate(Date contractEndDate) {
    this.contractEndDate = contractEndDate;
    return this;
  }

   /**
   * Get contractEndDate
   * @return contractEndDate
  **/
  @ApiModelProperty(value = "")
  public Date getContractEndDate() {
    return contractEndDate;
  }

  public void setContractEndDate(Date contractEndDate) {
    this.contractEndDate = contractEndDate;
  }

  public ApiModelV1CommonsDomainPriceAdjustment discountTieringLevels(List<ApiModelV1CommonsDomainDiscountTieringLevel> discountTieringLevels) {
    this.discountTieringLevels = discountTieringLevels;
    return this;
  }

  public ApiModelV1CommonsDomainPriceAdjustment addDiscountTieringLevelsItem(ApiModelV1CommonsDomainDiscountTieringLevel discountTieringLevelsItem) {
    if (this.discountTieringLevels == null) {
      this.discountTieringLevels = new ArrayList<ApiModelV1CommonsDomainDiscountTieringLevel>();
    }
    this.discountTieringLevels.add(discountTieringLevelsItem);
    return this;
  }

   /**
   * Get discountTieringLevels
   * @return discountTieringLevels
  **/
  @ApiModelProperty(value = "")
  public List<ApiModelV1CommonsDomainDiscountTieringLevel> getDiscountTieringLevels() {
    return discountTieringLevels;
  }

  public void setDiscountTieringLevels(List<ApiModelV1CommonsDomainDiscountTieringLevel> discountTieringLevels) {
    this.discountTieringLevels = discountTieringLevels;
  }

  public ApiModelV1CommonsDomainPriceAdjustment flagFallAmount(java.math.BigDecimal flagFallAmount) {
    this.flagFallAmount = flagFallAmount;
    return this;
  }

   /**
   * Get flagFallAmount
   * @return flagFallAmount
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getFlagFallAmount() {
    return flagFallAmount;
  }

  public void setFlagFallAmount(java.math.BigDecimal flagFallAmount) {
    this.flagFallAmount = flagFallAmount;
  }

  public ApiModelV1CommonsDomainPriceAdjustment fund(ApiModelV1CommonsDomainFundReference fund) {
    this.fund = fund;
    return this;
  }

   /**
   * Get fund
   * @return fund
  **/
  @ApiModelProperty(value = "")
  public ApiModelV1CommonsDomainFundReference getFund() {
    return fund;
  }

  public void setFund(ApiModelV1CommonsDomainFundReference fund) {
    this.fund = fund;
  }

  public ApiModelV1CommonsDomainPriceAdjustment fundAmount(java.math.BigDecimal fundAmount) {
    this.fundAmount = fundAmount;
    return this;
  }

   /**
   * Get fundAmount
   * @return fundAmount
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getFundAmount() {
    return fundAmount;
  }

  public void setFundAmount(java.math.BigDecimal fundAmount) {
    this.fundAmount = fundAmount;
  }

  public ApiModelV1CommonsDomainPriceAdjustment invoiceText(String invoiceText) {
    this.invoiceText = invoiceText;
    return this;
  }

   /**
   * Get invoiceText
   * @return invoiceText
  **/
  @ApiModelProperty(value = "")
  public String getInvoiceText() {
    return invoiceText;
  }

  public void setInvoiceText(String invoiceText) {
    this.invoiceText = invoiceText;
  }

  public ApiModelV1CommonsDomainPriceAdjustment loyaltyPoints(Integer loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
    return this;
  }

   /**
   * Get loyaltyPoints
   * @return loyaltyPoints
  **/
  @ApiModelProperty(value = "")
  public Integer getLoyaltyPoints() {
    return loyaltyPoints;
  }

  public void setLoyaltyPoints(Integer loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
  }

  public ApiModelV1CommonsDomainPriceAdjustment netCharge(java.math.BigDecimal netCharge) {
    this.netCharge = netCharge;
    return this;
  }

   /**
   * Get netCharge
   * @return netCharge
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getNetCharge() {
    return netCharge;
  }

  public void setNetCharge(java.math.BigDecimal netCharge) {
    this.netCharge = netCharge;
  }

  public ApiModelV1CommonsDomainPriceAdjustment numberOfPayments(Integer numberOfPayments) {
    this.numberOfPayments = numberOfPayments;
    return this;
  }

   /**
   * Get numberOfPayments
   * @return numberOfPayments
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfPayments() {
    return numberOfPayments;
  }

  public void setNumberOfPayments(Integer numberOfPayments) {
    this.numberOfPayments = numberOfPayments;
  }

  public ApiModelV1CommonsDomainPriceAdjustment previousNetCharge(java.math.BigDecimal previousNetCharge) {
    this.previousNetCharge = previousNetCharge;
    return this;
  }

   /**
   * Get previousNetCharge
   * @return previousNetCharge
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getPreviousNetCharge() {
    return previousNetCharge;
  }

  public void setPreviousNetCharge(java.math.BigDecimal previousNetCharge) {
    this.previousNetCharge = previousNetCharge;
  }

  public ApiModelV1CommonsDomainPriceAdjustment terminationCharge(java.math.BigDecimal terminationCharge) {
    this.terminationCharge = terminationCharge;
    return this;
  }

   /**
   * Get terminationCharge
   * @return terminationCharge
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getTerminationCharge() {
    return terminationCharge;
  }

  public void setTerminationCharge(java.math.BigDecimal terminationCharge) {
    this.terminationCharge = terminationCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiModelV1CommonsDomainPriceAdjustment apiModelV1CommonsDomainPriceAdjustment = (ApiModelV1CommonsDomainPriceAdjustment) o;
    return Objects.equals(this.allowanceAmount, apiModelV1CommonsDomainPriceAdjustment.allowanceAmount) &&
        Objects.equals(this.billText, apiModelV1CommonsDomainPriceAdjustment.billText) &&
        Objects.equals(this.contractEndDate, apiModelV1CommonsDomainPriceAdjustment.contractEndDate) &&
        Objects.equals(this.discountTieringLevels, apiModelV1CommonsDomainPriceAdjustment.discountTieringLevels) &&
        Objects.equals(this.flagFallAmount, apiModelV1CommonsDomainPriceAdjustment.flagFallAmount) &&
        Objects.equals(this.fund, apiModelV1CommonsDomainPriceAdjustment.fund) &&
        Objects.equals(this.fundAmount, apiModelV1CommonsDomainPriceAdjustment.fundAmount) &&
        Objects.equals(this.invoiceText, apiModelV1CommonsDomainPriceAdjustment.invoiceText) &&
        Objects.equals(this.loyaltyPoints, apiModelV1CommonsDomainPriceAdjustment.loyaltyPoints) &&
        Objects.equals(this.netCharge, apiModelV1CommonsDomainPriceAdjustment.netCharge) &&
        Objects.equals(this.numberOfPayments, apiModelV1CommonsDomainPriceAdjustment.numberOfPayments) &&
        Objects.equals(this.previousNetCharge, apiModelV1CommonsDomainPriceAdjustment.previousNetCharge) &&
        Objects.equals(this.terminationCharge, apiModelV1CommonsDomainPriceAdjustment.terminationCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowanceAmount, billText, contractEndDate, discountTieringLevels, flagFallAmount, fund, fundAmount, invoiceText, loyaltyPoints, netCharge, numberOfPayments, previousNetCharge, terminationCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiModelV1CommonsDomainPriceAdjustment {\n");
    
    sb.append("    allowanceAmount: ").append(toIndentedString(allowanceAmount)).append("\n");
    sb.append("    billText: ").append(toIndentedString(billText)).append("\n");
    sb.append("    contractEndDate: ").append(toIndentedString(contractEndDate)).append("\n");
    sb.append("    discountTieringLevels: ").append(toIndentedString(discountTieringLevels)).append("\n");
    sb.append("    flagFallAmount: ").append(toIndentedString(flagFallAmount)).append("\n");
    sb.append("    fund: ").append(toIndentedString(fund)).append("\n");
    sb.append("    fundAmount: ").append(toIndentedString(fundAmount)).append("\n");
    sb.append("    invoiceText: ").append(toIndentedString(invoiceText)).append("\n");
    sb.append("    loyaltyPoints: ").append(toIndentedString(loyaltyPoints)).append("\n");
    sb.append("    netCharge: ").append(toIndentedString(netCharge)).append("\n");
    sb.append("    numberOfPayments: ").append(toIndentedString(numberOfPayments)).append("\n");
    sb.append("    previousNetCharge: ").append(toIndentedString(previousNetCharge)).append("\n");
    sb.append("    terminationCharge: ").append(toIndentedString(terminationCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

