/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ApiModelV1CommonsDomainDiscountTieringLevel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ApiModelV1CommonsDomainDiscountTieringLevel {
  @JsonProperty("unitsMax")
  private Long unitsMax = null;

  @JsonProperty("unitsMin")
  private Long unitsMin = null;

  @JsonProperty("value")
  private java.math.BigDecimal value = null;

  public ApiModelV1CommonsDomainDiscountTieringLevel unitsMax(Long unitsMax) {
    this.unitsMax = unitsMax;
    return this;
  }

   /**
   * Get unitsMax
   * @return unitsMax
  **/
  @ApiModelProperty(value = "")
  public Long getUnitsMax() {
    return unitsMax;
  }

  public void setUnitsMax(Long unitsMax) {
    this.unitsMax = unitsMax;
  }

  public ApiModelV1CommonsDomainDiscountTieringLevel unitsMin(Long unitsMin) {
    this.unitsMin = unitsMin;
    return this;
  }

   /**
   * Get unitsMin
   * @return unitsMin
  **/
  @ApiModelProperty(value = "")
  public Long getUnitsMin() {
    return unitsMin;
  }

  public void setUnitsMin(Long unitsMin) {
    this.unitsMin = unitsMin;
  }

  public ApiModelV1CommonsDomainDiscountTieringLevel value(java.math.BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getValue() {
    return value;
  }

  public void setValue(java.math.BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiModelV1CommonsDomainDiscountTieringLevel apiModelV1CommonsDomainDiscountTieringLevel = (ApiModelV1CommonsDomainDiscountTieringLevel) o;
    return Objects.equals(this.unitsMax, apiModelV1CommonsDomainDiscountTieringLevel.unitsMax) &&
        Objects.equals(this.unitsMin, apiModelV1CommonsDomainDiscountTieringLevel.unitsMin) &&
        Objects.equals(this.value, apiModelV1CommonsDomainDiscountTieringLevel.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitsMax, unitsMin, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiModelV1CommonsDomainDiscountTieringLevel {\n");
    
    sb.append("    unitsMax: ").append(toIndentedString(unitsMax)).append("\n");
    sb.append("    unitsMin: ").append(toIndentedString(unitsMin)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

