/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import se.telia.infonova.model.ApiModelV1CommonsDomainValue;
import se.telia.infonova.model.ArPaymentDomainPaymentMethod;
import se.telia.infonova.model.CommonsDomainModelLink;
import se.telia.infonova.model.CommonsDomainModelRelatedObject;
import se.telia.infonova.model.PartyV1DomainRelatedParty;

/**
 * ArPaymentDomainPayment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ArPaymentDomainPayment {
  @JsonProperty("_links")
  private Map<String, CommonsDomainModelLink> links = null;

  @JsonProperty("acknowledged")
  private Date acknowledged = null;

  @JsonProperty("amount")
  private ApiModelV1CommonsDomainValue amount = null;

  @JsonProperty("created")
  private Date created = null;

  @JsonProperty("creator")
  private String creator = null;

  @JsonProperty("errorReason")
  private String errorReason = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("parameters")
  private Map<String, String> parameters = null;

  @JsonProperty("paymentMethod")
  private ArPaymentDomainPaymentMethod paymentMethod = null;

  @JsonProperty("paymentReference")
  private String paymentReference = null;

  @JsonProperty("pendingRefundAmount")
  private ApiModelV1CommonsDomainValue pendingRefundAmount = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("refundReference")
  private String refundReference = null;

  @JsonProperty("relatedObjects")
  private List<CommonsDomainModelRelatedObject> relatedObjects = null;

  @JsonProperty("relatedParties")
  private List<PartyV1DomainRelatedParty> relatedParties = null;

  @JsonProperty("settled")
  private Date settled = null;

  @JsonProperty("state")
  private String state = null;

  public ArPaymentDomainPayment links(Map<String, CommonsDomainModelLink> links) {
    this.links = links;
    return this;
  }

  public ArPaymentDomainPayment putLinksItem(String key, CommonsDomainModelLink linksItem) {
    if (this.links == null) {
      this.links = new HashMap<String, CommonsDomainModelLink>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public Map<String, CommonsDomainModelLink> getLinks() {
    return links;
  }

  public void setLinks(Map<String, CommonsDomainModelLink> links) {
    this.links = links;
  }

  public ArPaymentDomainPayment acknowledged(Date acknowledged) {
    this.acknowledged = acknowledged;
    return this;
  }

   /**
   * Get acknowledged
   * @return acknowledged
  **/
  @ApiModelProperty(value = "")
  public Date getAcknowledged() {
    return acknowledged;
  }

  public void setAcknowledged(Date acknowledged) {
    this.acknowledged = acknowledged;
  }

  public ArPaymentDomainPayment amount(ApiModelV1CommonsDomainValue amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public ApiModelV1CommonsDomainValue getAmount() {
    return amount;
  }

  public void setAmount(ApiModelV1CommonsDomainValue amount) {
    this.amount = amount;
  }

  public ArPaymentDomainPayment created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public ArPaymentDomainPayment creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @ApiModelProperty(value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public ArPaymentDomainPayment errorReason(String errorReason) {
    this.errorReason = errorReason;
    return this;
  }

   /**
   * Get errorReason
   * @return errorReason
  **/
  @ApiModelProperty(value = "")
  public String getErrorReason() {
    return errorReason;
  }

  public void setErrorReason(String errorReason) {
    this.errorReason = errorReason;
  }

  public ArPaymentDomainPayment externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ArPaymentDomainPayment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ArPaymentDomainPayment parameters(Map<String, String> parameters) {
    this.parameters = parameters;
    return this;
  }

  public ArPaymentDomainPayment putParametersItem(String key, String parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<String, String>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getParameters() {
    return parameters;
  }

  public void setParameters(Map<String, String> parameters) {
    this.parameters = parameters;
  }

  public ArPaymentDomainPayment paymentMethod(ArPaymentDomainPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(value = "")
  public ArPaymentDomainPaymentMethod getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(ArPaymentDomainPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public ArPaymentDomainPayment paymentReference(String paymentReference) {
    this.paymentReference = paymentReference;
    return this;
  }

   /**
   * Get paymentReference
   * @return paymentReference
  **/
  @ApiModelProperty(value = "")
  public String getPaymentReference() {
    return paymentReference;
  }

  public void setPaymentReference(String paymentReference) {
    this.paymentReference = paymentReference;
  }

  public ArPaymentDomainPayment pendingRefundAmount(ApiModelV1CommonsDomainValue pendingRefundAmount) {
    this.pendingRefundAmount = pendingRefundAmount;
    return this;
  }

   /**
   * Get pendingRefundAmount
   * @return pendingRefundAmount
  **/
  @ApiModelProperty(value = "")
  public ApiModelV1CommonsDomainValue getPendingRefundAmount() {
    return pendingRefundAmount;
  }

  public void setPendingRefundAmount(ApiModelV1CommonsDomainValue pendingRefundAmount) {
    this.pendingRefundAmount = pendingRefundAmount;
  }

  public ArPaymentDomainPayment reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ArPaymentDomainPayment refundReference(String refundReference) {
    this.refundReference = refundReference;
    return this;
  }

   /**
   * Get refundReference
   * @return refundReference
  **/
  @ApiModelProperty(value = "")
  public String getRefundReference() {
    return refundReference;
  }

  public void setRefundReference(String refundReference) {
    this.refundReference = refundReference;
  }

  public ArPaymentDomainPayment relatedObjects(List<CommonsDomainModelRelatedObject> relatedObjects) {
    this.relatedObjects = relatedObjects;
    return this;
  }

  public ArPaymentDomainPayment addRelatedObjectsItem(CommonsDomainModelRelatedObject relatedObjectsItem) {
    if (this.relatedObjects == null) {
      this.relatedObjects = new ArrayList<CommonsDomainModelRelatedObject>();
    }
    this.relatedObjects.add(relatedObjectsItem);
    return this;
  }

   /**
   * Get relatedObjects
   * @return relatedObjects
  **/
  @ApiModelProperty(value = "")
  public List<CommonsDomainModelRelatedObject> getRelatedObjects() {
    return relatedObjects;
  }

  public void setRelatedObjects(List<CommonsDomainModelRelatedObject> relatedObjects) {
    this.relatedObjects = relatedObjects;
  }

  public ArPaymentDomainPayment relatedParties(List<PartyV1DomainRelatedParty> relatedParties) {
    this.relatedParties = relatedParties;
    return this;
  }

  public ArPaymentDomainPayment addRelatedPartiesItem(PartyV1DomainRelatedParty relatedPartiesItem) {
    if (this.relatedParties == null) {
      this.relatedParties = new ArrayList<PartyV1DomainRelatedParty>();
    }
    this.relatedParties.add(relatedPartiesItem);
    return this;
  }

   /**
   * Get relatedParties
   * @return relatedParties
  **/
  @ApiModelProperty(value = "")
  public List<PartyV1DomainRelatedParty> getRelatedParties() {
    return relatedParties;
  }

  public void setRelatedParties(List<PartyV1DomainRelatedParty> relatedParties) {
    this.relatedParties = relatedParties;
  }

  public ArPaymentDomainPayment settled(Date settled) {
    this.settled = settled;
    return this;
  }

   /**
   * Get settled
   * @return settled
  **/
  @ApiModelProperty(value = "")
  public Date getSettled() {
    return settled;
  }

  public void setSettled(Date settled) {
    this.settled = settled;
  }

  public ArPaymentDomainPayment state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArPaymentDomainPayment arPaymentDomainPayment = (ArPaymentDomainPayment) o;
    return Objects.equals(this.links, arPaymentDomainPayment.links) &&
        Objects.equals(this.acknowledged, arPaymentDomainPayment.acknowledged) &&
        Objects.equals(this.amount, arPaymentDomainPayment.amount) &&
        Objects.equals(this.created, arPaymentDomainPayment.created) &&
        Objects.equals(this.creator, arPaymentDomainPayment.creator) &&
        Objects.equals(this.errorReason, arPaymentDomainPayment.errorReason) &&
        Objects.equals(this.externalId, arPaymentDomainPayment.externalId) &&
        Objects.equals(this.id, arPaymentDomainPayment.id) &&
        Objects.equals(this.parameters, arPaymentDomainPayment.parameters) &&
        Objects.equals(this.paymentMethod, arPaymentDomainPayment.paymentMethod) &&
        Objects.equals(this.paymentReference, arPaymentDomainPayment.paymentReference) &&
        Objects.equals(this.pendingRefundAmount, arPaymentDomainPayment.pendingRefundAmount) &&
        Objects.equals(this.reason, arPaymentDomainPayment.reason) &&
        Objects.equals(this.refundReference, arPaymentDomainPayment.refundReference) &&
        Objects.equals(this.relatedObjects, arPaymentDomainPayment.relatedObjects) &&
        Objects.equals(this.relatedParties, arPaymentDomainPayment.relatedParties) &&
        Objects.equals(this.settled, arPaymentDomainPayment.settled) &&
        Objects.equals(this.state, arPaymentDomainPayment.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, acknowledged, amount, created, creator, errorReason, externalId, id, parameters, paymentMethod, paymentReference, pendingRefundAmount, reason, refundReference, relatedObjects, relatedParties, settled, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArPaymentDomainPayment {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    acknowledged: ").append(toIndentedString(acknowledged)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    errorReason: ").append(toIndentedString(errorReason)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentReference: ").append(toIndentedString(paymentReference)).append("\n");
    sb.append("    pendingRefundAmount: ").append(toIndentedString(pendingRefundAmount)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    refundReference: ").append(toIndentedString(refundReference)).append("\n");
    sb.append("    relatedObjects: ").append(toIndentedString(relatedObjects)).append("\n");
    sb.append("    relatedParties: ").append(toIndentedString(relatedParties)).append("\n");
    sb.append("    settled: ").append(toIndentedString(settled)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

