/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import se.telia.infonova.model.ArPaymentDomainParameterDefinition;

/**
 * ArPaymentDomainPaymentType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ArPaymentDomainPaymentType {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("displayOrder")
  private Integer displayOrder = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("parameterDefinitions")
  private List<ArPaymentDomainParameterDefinition> parameterDefinitions = null;

  @JsonProperty("supportsDirectDebit")
  private Boolean supportsDirectDebit = null;

  public ArPaymentDomainPaymentType description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ArPaymentDomainPaymentType displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ArPaymentDomainPaymentType displayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
    return this;
  }

   /**
   * Get displayOrder
   * @return displayOrder
  **/
  @ApiModelProperty(value = "")
  public Integer getDisplayOrder() {
    return displayOrder;
  }

  public void setDisplayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
  }

  public ArPaymentDomainPaymentType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ArPaymentDomainPaymentType parameterDefinitions(List<ArPaymentDomainParameterDefinition> parameterDefinitions) {
    this.parameterDefinitions = parameterDefinitions;
    return this;
  }

  public ArPaymentDomainPaymentType addParameterDefinitionsItem(ArPaymentDomainParameterDefinition parameterDefinitionsItem) {
    if (this.parameterDefinitions == null) {
      this.parameterDefinitions = new ArrayList<ArPaymentDomainParameterDefinition>();
    }
    this.parameterDefinitions.add(parameterDefinitionsItem);
    return this;
  }

   /**
   * Get parameterDefinitions
   * @return parameterDefinitions
  **/
  @ApiModelProperty(value = "")
  public List<ArPaymentDomainParameterDefinition> getParameterDefinitions() {
    return parameterDefinitions;
  }

  public void setParameterDefinitions(List<ArPaymentDomainParameterDefinition> parameterDefinitions) {
    this.parameterDefinitions = parameterDefinitions;
  }

  public ArPaymentDomainPaymentType supportsDirectDebit(Boolean supportsDirectDebit) {
    this.supportsDirectDebit = supportsDirectDebit;
    return this;
  }

   /**
   * Get supportsDirectDebit
   * @return supportsDirectDebit
  **/
  @ApiModelProperty(value = "")
  public Boolean isSupportsDirectDebit() {
    return supportsDirectDebit;
  }

  public void setSupportsDirectDebit(Boolean supportsDirectDebit) {
    this.supportsDirectDebit = supportsDirectDebit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArPaymentDomainPaymentType arPaymentDomainPaymentType = (ArPaymentDomainPaymentType) o;
    return Objects.equals(this.description, arPaymentDomainPaymentType.description) &&
        Objects.equals(this.displayName, arPaymentDomainPaymentType.displayName) &&
        Objects.equals(this.displayOrder, arPaymentDomainPaymentType.displayOrder) &&
        Objects.equals(this.name, arPaymentDomainPaymentType.name) &&
        Objects.equals(this.parameterDefinitions, arPaymentDomainPaymentType.parameterDefinitions) &&
        Objects.equals(this.supportsDirectDebit, arPaymentDomainPaymentType.supportsDirectDebit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displayName, displayOrder, name, parameterDefinitions, supportsDirectDebit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArPaymentDomainPaymentType {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    displayOrder: ").append(toIndentedString(displayOrder)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parameterDefinitions: ").append(toIndentedString(parameterDefinitions)).append("\n");
    sb.append("    supportsDirectDebit: ").append(toIndentedString(supportsDirectDebit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

