/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ArPaymentDomainPaymentListPaginationInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ArPaymentDomainPaymentListPaginationInformation {
  @JsonProperty("pageSize")
  private Integer pageSize = null;

  @JsonProperty("totalNumberOfRecords")
  private Integer totalNumberOfRecords = null;

  public ArPaymentDomainPaymentListPaginationInformation pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public ArPaymentDomainPaymentListPaginationInformation totalNumberOfRecords(Integer totalNumberOfRecords) {
    this.totalNumberOfRecords = totalNumberOfRecords;
    return this;
  }

   /**
   * Get totalNumberOfRecords
   * @return totalNumberOfRecords
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalNumberOfRecords() {
    return totalNumberOfRecords;
  }

  public void setTotalNumberOfRecords(Integer totalNumberOfRecords) {
    this.totalNumberOfRecords = totalNumberOfRecords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArPaymentDomainPaymentListPaginationInformation arPaymentDomainPaymentListPaginationInformation = (ArPaymentDomainPaymentListPaginationInformation) o;
    return Objects.equals(this.pageSize, arPaymentDomainPaymentListPaginationInformation.pageSize) &&
        Objects.equals(this.totalNumberOfRecords, arPaymentDomainPaymentListPaginationInformation.totalNumberOfRecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageSize, totalNumberOfRecords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArPaymentDomainPaymentListPaginationInformation {\n");
    
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalNumberOfRecords: ").append(toIndentedString(totalNumberOfRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

