/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ArV1FinancialaccountDomainFinancialAccountBalances
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class ArV1FinancialaccountDomainFinancialAccountBalances {
  @JsonProperty("accountBalance")
  private java.math.BigDecimal accountBalance = null;

  @JsonProperty("overdueBalance")
  private java.math.BigDecimal overdueBalance = null;

  @JsonProperty("writeOffBalance")
  private java.math.BigDecimal writeOffBalance = null;

  public ArV1FinancialaccountDomainFinancialAccountBalances accountBalance(java.math.BigDecimal accountBalance) {
    this.accountBalance = accountBalance;
    return this;
  }

   /**
   * Get accountBalance
   * @return accountBalance
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getAccountBalance() {
    return accountBalance;
  }

  public void setAccountBalance(java.math.BigDecimal accountBalance) {
    this.accountBalance = accountBalance;
  }

  public ArV1FinancialaccountDomainFinancialAccountBalances overdueBalance(java.math.BigDecimal overdueBalance) {
    this.overdueBalance = overdueBalance;
    return this;
  }

   /**
   * Get overdueBalance
   * @return overdueBalance
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getOverdueBalance() {
    return overdueBalance;
  }

  public void setOverdueBalance(java.math.BigDecimal overdueBalance) {
    this.overdueBalance = overdueBalance;
  }

  public ArV1FinancialaccountDomainFinancialAccountBalances writeOffBalance(java.math.BigDecimal writeOffBalance) {
    this.writeOffBalance = writeOffBalance;
    return this;
  }

   /**
   * Get writeOffBalance
   * @return writeOffBalance
  **/
  @ApiModelProperty(value = "")
  public java.math.BigDecimal getWriteOffBalance() {
    return writeOffBalance;
  }

  public void setWriteOffBalance(java.math.BigDecimal writeOffBalance) {
    this.writeOffBalance = writeOffBalance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArV1FinancialaccountDomainFinancialAccountBalances arV1FinancialaccountDomainFinancialAccountBalances = (ArV1FinancialaccountDomainFinancialAccountBalances) o;
    return Objects.equals(this.accountBalance, arV1FinancialaccountDomainFinancialAccountBalances.accountBalance) &&
        Objects.equals(this.overdueBalance, arV1FinancialaccountDomainFinancialAccountBalances.overdueBalance) &&
        Objects.equals(this.writeOffBalance, arV1FinancialaccountDomainFinancialAccountBalances.writeOffBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountBalance, overdueBalance, writeOffBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArV1FinancialaccountDomainFinancialAccountBalances {\n");
    
    sb.append("    accountBalance: ").append(toIndentedString(accountBalance)).append("\n");
    sb.append("    overdueBalance: ").append(toIndentedString(overdueBalance)).append("\n");
    sb.append("    writeOffBalance: ").append(toIndentedString(writeOffBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

