/*
 * Infonova API Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.telia.infonova.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import se.telia.infonova.model.ArPaymentDomainPaymentListPaginationInformation;
import se.telia.infonova.model.BalanceV1DomainBalance;

/**
 * BalanceV1DomainBalanceList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-07T15:46:38.398+01:00")
public class BalanceV1DomainBalanceList {
  @JsonProperty("list")
  private List<BalanceV1DomainBalance> _list = null;

  @JsonProperty("paginationInformation")
  private ArPaymentDomainPaymentListPaginationInformation paginationInformation = null;

  public BalanceV1DomainBalanceList _list(List<BalanceV1DomainBalance> _list) {
    this._list = _list;
    return this;
  }

  public BalanceV1DomainBalanceList addListItem(BalanceV1DomainBalance _listItem) {
    if (this._list == null) {
      this._list = new ArrayList<BalanceV1DomainBalance>();
    }
    this._list.add(_listItem);
    return this;
  }

   /**
   * Get _list
   * @return _list
  **/
  @ApiModelProperty(value = "")
  public List<BalanceV1DomainBalance> getList() {
    return _list;
  }

  public void setList(List<BalanceV1DomainBalance> _list) {
    this._list = _list;
  }

  public BalanceV1DomainBalanceList paginationInformation(ArPaymentDomainPaymentListPaginationInformation paginationInformation) {
    this.paginationInformation = paginationInformation;
    return this;
  }

   /**
   * Get paginationInformation
   * @return paginationInformation
  **/
  @ApiModelProperty(value = "")
  public ArPaymentDomainPaymentListPaginationInformation getPaginationInformation() {
    return paginationInformation;
  }

  public void setPaginationInformation(ArPaymentDomainPaymentListPaginationInformation paginationInformation) {
    this.paginationInformation = paginationInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceV1DomainBalanceList balanceV1DomainBalanceList = (BalanceV1DomainBalanceList) o;
    return Objects.equals(this._list, balanceV1DomainBalanceList._list) &&
        Objects.equals(this.paginationInformation, balanceV1DomainBalanceList.paginationInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_list, paginationInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceV1DomainBalanceList {\n");
    
    sb.append("    _list: ").append(toIndentedString(_list)).append("\n");
    sb.append("    paginationInformation: ").append(toIndentedString(paginationInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

